// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service/exchange.proto
#ifndef GRPC_service_2fexchange_2eproto__INCLUDED
#define GRPC_service_2fexchange_2eproto__INCLUDED

#include "service/exchange.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace service {

// *****************************
// * Exchange APIs and objects *
// *****************************
class ExchangeService final {
 public:
  static constexpr char const* service_full_name() {
    return "service.ExchangeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::service::GetExchangeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetExchangeResponse>> AsyncGetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetExchangeResponse>>(AsyncGetExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetExchangeResponse>> PrepareAsyncGetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetExchangeResponse>>(PrepareAsyncGetExchangeRaw(context, request, cq));
    }
    virtual ::grpc::Status ListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::service::ListExchangesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListExchangesResponse>> AsyncListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListExchangesResponse>>(AsyncListExchangesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListExchangesResponse>> PrepareAsyncListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListExchangesResponse>>(PrepareAsyncListExchangesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest* request, ::service::GetExchangeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest* request, ::service::GetExchangeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest* request, ::service::ListExchangesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest* request, ::service::ListExchangesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::GetExchangeResponse>* AsyncGetExchangeRaw(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::GetExchangeResponse>* PrepareAsyncGetExchangeRaw(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::ListExchangesResponse>* AsyncListExchangesRaw(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::ListExchangesResponse>* PrepareAsyncListExchangesRaw(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::service::GetExchangeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetExchangeResponse>> AsyncGetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetExchangeResponse>>(AsyncGetExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetExchangeResponse>> PrepareAsyncGetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetExchangeResponse>>(PrepareAsyncGetExchangeRaw(context, request, cq));
    }
    ::grpc::Status ListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::service::ListExchangesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListExchangesResponse>> AsyncListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListExchangesResponse>>(AsyncListExchangesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListExchangesResponse>> PrepareAsyncListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListExchangesResponse>>(PrepareAsyncListExchangesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest* request, ::service::GetExchangeResponse* response, std::function<void(::grpc::Status)>) override;
      void GetExchange(::grpc::ClientContext* context, const ::service::GetExchangeRequest* request, ::service::GetExchangeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest* request, ::service::ListExchangesResponse* response, std::function<void(::grpc::Status)>) override;
      void ListExchanges(::grpc::ClientContext* context, const ::service::ListExchangesRequest* request, ::service::ListExchangesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::service::GetExchangeResponse>* AsyncGetExchangeRaw(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::GetExchangeResponse>* PrepareAsyncGetExchangeRaw(::grpc::ClientContext* context, const ::service::GetExchangeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::ListExchangesResponse>* AsyncListExchangesRaw(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::ListExchangesResponse>* PrepareAsyncListExchangesRaw(::grpc::ClientContext* context, const ::service::ListExchangesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetExchange_;
    const ::grpc::internal::RpcMethod rpcmethod_ListExchanges_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetExchange(::grpc::ServerContext* context, const ::service::GetExchangeRequest* request, ::service::GetExchangeResponse* response);
    virtual ::grpc::Status ListExchanges(::grpc::ServerContext* context, const ::service::ListExchangesRequest* request, ::service::ListExchangesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetExchange() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetExchange(::grpc::ServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetExchange(::grpc::ServerContext* context, ::service::GetExchangeRequest* request, ::grpc::ServerAsyncResponseWriter< ::service::GetExchangeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListExchanges : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListExchanges() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListExchanges() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListExchanges(::grpc::ServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListExchanges(::grpc::ServerContext* context, ::service::ListExchangesRequest* request, ::grpc::ServerAsyncResponseWriter< ::service::ListExchangesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetExchange<WithAsyncMethod_ListExchanges<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetExchange() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::service::GetExchangeRequest, ::service::GetExchangeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::service::GetExchangeRequest* request, ::service::GetExchangeResponse* response) { return this->GetExchange(context, request, response); }));}
    void SetMessageAllocatorFor_GetExchange(
        ::grpc::MessageAllocator< ::service::GetExchangeRequest, ::service::GetExchangeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::service::GetExchangeRequest, ::service::GetExchangeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetExchange(::grpc::ServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetExchange(
      ::grpc::CallbackServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListExchanges : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListExchanges() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::service::ListExchangesRequest, ::service::ListExchangesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::service::ListExchangesRequest* request, ::service::ListExchangesResponse* response) { return this->ListExchanges(context, request, response); }));}
    void SetMessageAllocatorFor_ListExchanges(
        ::grpc::MessageAllocator< ::service::ListExchangesRequest, ::service::ListExchangesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::service::ListExchangesRequest, ::service::ListExchangesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListExchanges() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListExchanges(::grpc::ServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListExchanges(
      ::grpc::CallbackServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetExchange<WithCallbackMethod_ListExchanges<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetExchange() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetExchange(::grpc::ServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListExchanges : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListExchanges() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListExchanges() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListExchanges(::grpc::ServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetExchange() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetExchange(::grpc::ServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetExchange(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListExchanges : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListExchanges() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListExchanges() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListExchanges(::grpc::ServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListExchanges(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetExchange() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetExchange(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetExchange(::grpc::ServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetExchange(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListExchanges : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListExchanges() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListExchanges(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListExchanges() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListExchanges(::grpc::ServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListExchanges(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetExchange() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::service::GetExchangeRequest, ::service::GetExchangeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::service::GetExchangeRequest, ::service::GetExchangeResponse>* streamer) {
                       return this->StreamedGetExchange(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetExchange(::grpc::ServerContext* /*context*/, const ::service::GetExchangeRequest* /*request*/, ::service::GetExchangeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetExchange(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::service::GetExchangeRequest,::service::GetExchangeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListExchanges : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListExchanges() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::service::ListExchangesRequest, ::service::ListExchangesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::service::ListExchangesRequest, ::service::ListExchangesResponse>* streamer) {
                       return this->StreamedListExchanges(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListExchanges() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListExchanges(::grpc::ServerContext* /*context*/, const ::service::ListExchangesRequest* /*request*/, ::service::ListExchangesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListExchanges(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::service::ListExchangesRequest,::service::ListExchangesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetExchange<WithStreamedUnaryMethod_ListExchanges<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetExchange<WithStreamedUnaryMethod_ListExchanges<Service > > StreamedService;
};

}  // namespace service


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_service_2fexchange_2eproto__INCLUDED
