// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/security.proto
// Protobuf C++ Version: 6.31.1

#include "service/security.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace service {

inline constexpr ListSecuritiesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        page_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        page_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListSecuritiesRequest::ListSecuritiesRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ListSecuritiesRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListSecuritiesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListSecuritiesRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListSecuritiesRequestDefaultTypeInternal() {}
  union {
    ListSecuritiesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListSecuritiesRequestDefaultTypeInternal _ListSecuritiesRequest_default_instance_;

inline constexpr GetSecurityRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR GetSecurityRequest::GetSecurityRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetSecurityRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetSecurityRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetSecurityRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetSecurityRequestDefaultTypeInternal() {}
  union {
    GetSecurityRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetSecurityRequestDefaultTypeInternal _GetSecurityRequest_default_instance_;

inline constexpr Security::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        full_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        current_price_{nullptr},
        current_pe_ratio_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Security::Security(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Security_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SecurityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SecurityDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SecurityDefaultTypeInternal() {}
  union {
    Security _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SecurityDefaultTypeInternal _Security_default_instance_;

inline constexpr ListSecuritiesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        securities_{},
        next_page_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ListSecuritiesResponse::ListSecuritiesResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ListSecuritiesResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListSecuritiesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListSecuritiesResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListSecuritiesResponseDefaultTypeInternal() {}
  union {
    ListSecuritiesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListSecuritiesResponseDefaultTypeInternal _ListSecuritiesResponse_default_instance_;

inline constexpr GetSecurityResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        security_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR GetSecurityResponse::GetSecurityResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetSecurityResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetSecurityResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetSecurityResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetSecurityResponseDefaultTypeInternal() {}
  union {
    GetSecurityResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetSecurityResponseDefaultTypeInternal _GetSecurityResponse_default_instance_;
}  // namespace service
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_service_2fsecurity_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_service_2fsecurity_2eproto = nullptr;
const ::uint32_t
    TableStruct_service_2fsecurity_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::service::GetSecurityRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::service::GetSecurityRequest, _impl_.symbol_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::service::GetSecurityResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::service::GetSecurityResponse, _impl_.security_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::service::ListSecuritiesRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::service::ListSecuritiesRequest, _impl_.page_size_),
        PROTOBUF_FIELD_OFFSET(::service::ListSecuritiesRequest, _impl_.page_token_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::service::ListSecuritiesResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::service::ListSecuritiesResponse, _impl_.securities_),
        PROTOBUF_FIELD_OFFSET(::service::ListSecuritiesResponse, _impl_.next_page_token_),
        ~0u,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::service::Security, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::service::Security, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::service::Security, _impl_.full_name_),
        PROTOBUF_FIELD_OFFSET(::service::Security, _impl_.current_price_),
        PROTOBUF_FIELD_OFFSET(::service::Security, _impl_.current_pe_ratio_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::service::GetSecurityRequest)},
        {5, sizeof(::service::GetSecurityResponse)},
        {10, sizeof(::service::ListSecuritiesRequest)},
        {17, sizeof(::service::ListSecuritiesResponse)},
        {24, sizeof(::service::Security)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::service::_GetSecurityRequest_default_instance_._instance,
    &::service::_GetSecurityResponse_default_instance_._instance,
    &::service::_ListSecuritiesRequest_default_instance_._instance,
    &::service::_ListSecuritiesResponse_default_instance_._instance,
    &::service::_Security_default_instance_._instance,
};
const char descriptor_table_protodef_service_2fsecurity_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026service/security.proto\022\007service\032\022commo"
    "n/types.proto\"$\n\022GetSecurityRequest\022\016\n\006s"
    "ymbol\030\001 \001(\t\":\n\023GetSecurityResponse\022#\n\010se"
    "curity\030\001 \001(\0132\021.service.Security\">\n\025ListS"
    "ecuritiesRequest\022\021\n\tpage_size\030\001 \001(\005\022\022\n\np"
    "age_token\030\002 \001(\t\"X\n\026ListSecuritiesRespons"
    "e\022%\n\nsecurities\030\001 \003(\0132\021.service.Security"
    "\022\027\n\017next_page_token\030\002 \001(\t\"m\n\010Security\022\016\n"
    "\006symbol\030\001 \001(\t\022\021\n\tfull_name\030\002 \001(\t\022$\n\rcurr"
    "ent_price\030\003 \001(\0132\r.common.Money\022\030\n\020curren"
    "t_pe_ratio\030\004 \001(\0022\256\001\n\017SecurityService\022H\n\013"
    "GetSecurity\022\033.service.GetSecurityRequest"
    "\032\034.service.GetSecurityResponse\022Q\n\016ListSe"
    "curities\022\036.service.ListSecuritiesRequest"
    "\032\037.service.ListSecuritiesResponseb\006proto"
    "3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_service_2fsecurity_2eproto_deps[1] = {
        &::descriptor_table_common_2ftypes_2eproto,
};
static ::absl::once_flag descriptor_table_service_2fsecurity_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_service_2fsecurity_2eproto = {
    false,
    false,
    601,
    descriptor_table_protodef_service_2fsecurity_2eproto,
    "service/security.proto",
    &descriptor_table_service_2fsecurity_2eproto_once,
    descriptor_table_service_2fsecurity_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_service_2fsecurity_2eproto::offsets,
    file_level_enum_descriptors_service_2fsecurity_2eproto,
    file_level_service_descriptors_service_2fsecurity_2eproto,
};
namespace service {
// ===================================================================

class GetSecurityRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetSecurityRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetSecurityRequest, _impl_._has_bits_);
};

GetSecurityRequest::GetSecurityRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetSecurityRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.GetSecurityRequest)
}
PROTOBUF_NDEBUG_INLINE GetSecurityRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::service::GetSecurityRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        symbol_(arena, from.symbol_) {}

GetSecurityRequest::GetSecurityRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetSecurityRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetSecurityRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetSecurityRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:service.GetSecurityRequest)
}
PROTOBUF_NDEBUG_INLINE GetSecurityRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        symbol_(arena) {}

inline void GetSecurityRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetSecurityRequest::~GetSecurityRequest() {
  // @@protoc_insertion_point(destructor:service.GetSecurityRequest)
  SharedDtor(*this);
}
inline void GetSecurityRequest::SharedDtor(MessageLite& self) {
  GetSecurityRequest& this_ = static_cast<GetSecurityRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.symbol_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetSecurityRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetSecurityRequest(arena);
}
constexpr auto GetSecurityRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetSecurityRequest),
                                            alignof(GetSecurityRequest));
}
constexpr auto GetSecurityRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetSecurityRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetSecurityRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetSecurityRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetSecurityRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetSecurityRequest>(), &GetSecurityRequest::ByteSizeLong,
              &GetSecurityRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetSecurityRequest, _impl_._cached_size_),
          false,
      },
      &GetSecurityRequest::kDescriptorMethods,
      &descriptor_table_service_2fsecurity_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetSecurityRequest_class_data_ =
        GetSecurityRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetSecurityRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetSecurityRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetSecurityRequest_class_data_.tc_table);
  return GetSecurityRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 41, 2>
GetSecurityRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetSecurityRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetSecurityRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::GetSecurityRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string symbol = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(GetSecurityRequest, _impl_.symbol_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string symbol = 1;
    {PROTOBUF_FIELD_OFFSET(GetSecurityRequest, _impl_.symbol_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\6\0\0\0\0\0\0"
    "service.GetSecurityRequest"
    "symbol"
  }},
};
PROTOBUF_NOINLINE void GetSecurityRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:service.GetSecurityRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.symbol_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetSecurityRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetSecurityRequest& this_ = static_cast<const GetSecurityRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetSecurityRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetSecurityRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:service.GetSecurityRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string symbol = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_symbol().empty()) {
      const ::std::string& _s = this_._internal_symbol();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.GetSecurityRequest.symbol");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.GetSecurityRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetSecurityRequest::ByteSizeLong(const MessageLite& base) {
  const GetSecurityRequest& this_ = static_cast<const GetSecurityRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetSecurityRequest::ByteSizeLong() const {
  const GetSecurityRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:service.GetSecurityRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string symbol = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_symbol().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_symbol());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetSecurityRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetSecurityRequest*>(&to_msg);
  auto& from = static_cast<const GetSecurityRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.GetSecurityRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_symbol().empty()) {
      _this->_internal_set_symbol(from._internal_symbol());
    } else {
      if (_this->_impl_.symbol_.IsDefault()) {
        _this->_internal_set_symbol("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetSecurityRequest::CopyFrom(const GetSecurityRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.GetSecurityRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetSecurityRequest::InternalSwap(GetSecurityRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
}

::google::protobuf::Metadata GetSecurityRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetSecurityResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetSecurityResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetSecurityResponse, _impl_._has_bits_);
};

GetSecurityResponse::GetSecurityResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetSecurityResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.GetSecurityResponse)
}
PROTOBUF_NDEBUG_INLINE GetSecurityResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::service::GetSecurityResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GetSecurityResponse::GetSecurityResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetSecurityResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetSecurityResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetSecurityResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.security_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.security_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:service.GetSecurityResponse)
}
PROTOBUF_NDEBUG_INLINE GetSecurityResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GetSecurityResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.security_ = {};
}
GetSecurityResponse::~GetSecurityResponse() {
  // @@protoc_insertion_point(destructor:service.GetSecurityResponse)
  SharedDtor(*this);
}
inline void GetSecurityResponse::SharedDtor(MessageLite& self) {
  GetSecurityResponse& this_ = static_cast<GetSecurityResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.security_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetSecurityResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetSecurityResponse(arena);
}
constexpr auto GetSecurityResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetSecurityResponse),
                                            alignof(GetSecurityResponse));
}
constexpr auto GetSecurityResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetSecurityResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetSecurityResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetSecurityResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetSecurityResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetSecurityResponse>(), &GetSecurityResponse::ByteSizeLong,
              &GetSecurityResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetSecurityResponse, _impl_._cached_size_),
          false,
      },
      &GetSecurityResponse::kDescriptorMethods,
      &descriptor_table_service_2fsecurity_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetSecurityResponse_class_data_ =
        GetSecurityResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetSecurityResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetSecurityResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetSecurityResponse_class_data_.tc_table);
  return GetSecurityResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
GetSecurityResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetSecurityResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GetSecurityResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::GetSecurityResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .service.Security security = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(GetSecurityResponse, _impl_.security_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .service.Security security = 1;
    {PROTOBUF_FIELD_OFFSET(GetSecurityResponse, _impl_.security_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::service::Security>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void GetSecurityResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:service.GetSecurityResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.security_ != nullptr);
    _impl_.security_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetSecurityResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetSecurityResponse& this_ = static_cast<const GetSecurityResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetSecurityResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetSecurityResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:service.GetSecurityResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .service.Security security = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.security_, this_._impl_.security_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.GetSecurityResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetSecurityResponse::ByteSizeLong(const MessageLite& base) {
  const GetSecurityResponse& this_ = static_cast<const GetSecurityResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetSecurityResponse::ByteSizeLong() const {
  const GetSecurityResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:service.GetSecurityResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .service.Security security = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.security_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetSecurityResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetSecurityResponse*>(&to_msg);
  auto& from = static_cast<const GetSecurityResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:service.GetSecurityResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(from._impl_.security_ != nullptr);
    if (_this->_impl_.security_ == nullptr) {
      _this->_impl_.security_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.security_);
    } else {
      _this->_impl_.security_->MergeFrom(*from._impl_.security_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetSecurityResponse::CopyFrom(const GetSecurityResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.GetSecurityResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetSecurityResponse::InternalSwap(GetSecurityResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.security_, other->_impl_.security_);
}

::google::protobuf::Metadata GetSecurityResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListSecuritiesRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ListSecuritiesRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_._has_bits_);
};

ListSecuritiesRequest::ListSecuritiesRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ListSecuritiesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.ListSecuritiesRequest)
}
PROTOBUF_NDEBUG_INLINE ListSecuritiesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::service::ListSecuritiesRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        page_token_(arena, from.page_token_) {}

ListSecuritiesRequest::ListSecuritiesRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ListSecuritiesRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ListSecuritiesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListSecuritiesRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.page_size_ = from._impl_.page_size_;

  // @@protoc_insertion_point(copy_constructor:service.ListSecuritiesRequest)
}
PROTOBUF_NDEBUG_INLINE ListSecuritiesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        page_token_(arena) {}

inline void ListSecuritiesRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.page_size_ = {};
}
ListSecuritiesRequest::~ListSecuritiesRequest() {
  // @@protoc_insertion_point(destructor:service.ListSecuritiesRequest)
  SharedDtor(*this);
}
inline void ListSecuritiesRequest::SharedDtor(MessageLite& self) {
  ListSecuritiesRequest& this_ = static_cast<ListSecuritiesRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.page_token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ListSecuritiesRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ListSecuritiesRequest(arena);
}
constexpr auto ListSecuritiesRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ListSecuritiesRequest),
                                            alignof(ListSecuritiesRequest));
}
constexpr auto ListSecuritiesRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ListSecuritiesRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ListSecuritiesRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ListSecuritiesRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ListSecuritiesRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ListSecuritiesRequest>(), &ListSecuritiesRequest::ByteSizeLong,
              &ListSecuritiesRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_._cached_size_),
          false,
      },
      &ListSecuritiesRequest::kDescriptorMethods,
      &descriptor_table_service_2fsecurity_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ListSecuritiesRequest_class_data_ =
        ListSecuritiesRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ListSecuritiesRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ListSecuritiesRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ListSecuritiesRequest_class_data_.tc_table);
  return ListSecuritiesRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 48, 2>
ListSecuritiesRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ListSecuritiesRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::ListSecuritiesRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string page_token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_.page_token_)}},
    // int32 page_size = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ListSecuritiesRequest, _impl_.page_size_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_.page_size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 page_size = 1;
    {PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_.page_size_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string page_token = 2;
    {PROTOBUF_FIELD_OFFSET(ListSecuritiesRequest, _impl_.page_token_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\0\12\0\0\0\0\0"
    "service.ListSecuritiesRequest"
    "page_token"
  }},
};
PROTOBUF_NOINLINE void ListSecuritiesRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:service.ListSecuritiesRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.page_token_.ClearNonDefaultToEmpty();
  }
  _impl_.page_size_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ListSecuritiesRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ListSecuritiesRequest& this_ = static_cast<const ListSecuritiesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ListSecuritiesRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ListSecuritiesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:service.ListSecuritiesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 page_size = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_page_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_page_size(), target);
    }
  }

  // string page_token = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_page_token().empty()) {
      const ::std::string& _s = this_._internal_page_token();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.ListSecuritiesRequest.page_token");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.ListSecuritiesRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ListSecuritiesRequest::ByteSizeLong(const MessageLite& base) {
  const ListSecuritiesRequest& this_ = static_cast<const ListSecuritiesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ListSecuritiesRequest::ByteSizeLong() const {
  const ListSecuritiesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:service.ListSecuritiesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string page_token = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_page_token().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_page_token());
      }
    }
    // int32 page_size = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_page_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_page_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ListSecuritiesRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListSecuritiesRequest*>(&to_msg);
  auto& from = static_cast<const ListSecuritiesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.ListSecuritiesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_page_token().empty()) {
        _this->_internal_set_page_token(from._internal_page_token());
      } else {
        if (_this->_impl_.page_token_.IsDefault()) {
          _this->_internal_set_page_token("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_page_size() != 0) {
        _this->_impl_.page_size_ = from._impl_.page_size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListSecuritiesRequest::CopyFrom(const ListSecuritiesRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.ListSecuritiesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListSecuritiesRequest::InternalSwap(ListSecuritiesRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.page_token_, &other->_impl_.page_token_, arena);
  swap(_impl_.page_size_, other->_impl_.page_size_);
}

::google::protobuf::Metadata ListSecuritiesRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListSecuritiesResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ListSecuritiesResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_._has_bits_);
};

ListSecuritiesResponse::ListSecuritiesResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ListSecuritiesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.ListSecuritiesResponse)
}
PROTOBUF_NDEBUG_INLINE ListSecuritiesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::service::ListSecuritiesResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        securities_{visibility, arena, from.securities_},
        next_page_token_(arena, from.next_page_token_) {}

ListSecuritiesResponse::ListSecuritiesResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ListSecuritiesResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ListSecuritiesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListSecuritiesResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:service.ListSecuritiesResponse)
}
PROTOBUF_NDEBUG_INLINE ListSecuritiesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        securities_{visibility, arena},
        next_page_token_(arena) {}

inline void ListSecuritiesResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListSecuritiesResponse::~ListSecuritiesResponse() {
  // @@protoc_insertion_point(destructor:service.ListSecuritiesResponse)
  SharedDtor(*this);
}
inline void ListSecuritiesResponse::SharedDtor(MessageLite& self) {
  ListSecuritiesResponse& this_ = static_cast<ListSecuritiesResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.next_page_token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ListSecuritiesResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ListSecuritiesResponse(arena);
}
constexpr auto ListSecuritiesResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_.securities_) +
          decltype(ListSecuritiesResponse::_impl_.securities_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ListSecuritiesResponse), alignof(ListSecuritiesResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ListSecuritiesResponse::PlacementNew_,
                                 sizeof(ListSecuritiesResponse),
                                 alignof(ListSecuritiesResponse));
  }
}
constexpr auto ListSecuritiesResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ListSecuritiesResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ListSecuritiesResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ListSecuritiesResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ListSecuritiesResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ListSecuritiesResponse>(), &ListSecuritiesResponse::ByteSizeLong,
              &ListSecuritiesResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_._cached_size_),
          false,
      },
      &ListSecuritiesResponse::kDescriptorMethods,
      &descriptor_table_service_2fsecurity_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ListSecuritiesResponse_class_data_ =
        ListSecuritiesResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ListSecuritiesResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ListSecuritiesResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ListSecuritiesResponse_class_data_.tc_table);
  return ListSecuritiesResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 54, 2>
ListSecuritiesResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ListSecuritiesResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::ListSecuritiesResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string next_page_token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_.next_page_token_)}},
    // repeated .service.Security securities = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_.securities_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .service.Security securities = 1;
    {PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_.securities_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string next_page_token = 2;
    {PROTOBUF_FIELD_OFFSET(ListSecuritiesResponse, _impl_.next_page_token_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::service::Security>()},
  }},
  {{
    "\36\0\17\0\0\0\0\0"
    "service.ListSecuritiesResponse"
    "next_page_token"
  }},
};
PROTOBUF_NOINLINE void ListSecuritiesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:service.ListSecuritiesResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.securities_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.next_page_token_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ListSecuritiesResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ListSecuritiesResponse& this_ = static_cast<const ListSecuritiesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ListSecuritiesResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ListSecuritiesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:service.ListSecuritiesResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .service.Security securities = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_securities_size());
       i < n; i++) {
    const auto& repfield = this_._internal_securities().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // string next_page_token = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_next_page_token().empty()) {
      const ::std::string& _s = this_._internal_next_page_token();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.ListSecuritiesResponse.next_page_token");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.ListSecuritiesResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ListSecuritiesResponse::ByteSizeLong(const MessageLite& base) {
  const ListSecuritiesResponse& this_ = static_cast<const ListSecuritiesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ListSecuritiesResponse::ByteSizeLong() const {
  const ListSecuritiesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:service.ListSecuritiesResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .service.Security securities = 1;
    {
      total_size += 1UL * this_._internal_securities_size();
      for (const auto& msg : this_._internal_securities()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // string next_page_token = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_next_page_token().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_next_page_token());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ListSecuritiesResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListSecuritiesResponse*>(&to_msg);
  auto& from = static_cast<const ListSecuritiesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.ListSecuritiesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_securities()->MergeFrom(
      from._internal_securities());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_next_page_token().empty()) {
      _this->_internal_set_next_page_token(from._internal_next_page_token());
    } else {
      if (_this->_impl_.next_page_token_.IsDefault()) {
        _this->_internal_set_next_page_token("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListSecuritiesResponse::CopyFrom(const ListSecuritiesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.ListSecuritiesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListSecuritiesResponse::InternalSwap(ListSecuritiesResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.securities_.InternalSwap(&other->_impl_.securities_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.next_page_token_, &other->_impl_.next_page_token_, arena);
}

::google::protobuf::Metadata ListSecuritiesResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Security::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Security>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Security, _impl_._has_bits_);
};

void Security::clear_current_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.current_price_ != nullptr) _impl_.current_price_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
Security::Security(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Security_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.Security)
}
PROTOBUF_NDEBUG_INLINE Security::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::service::Security& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        symbol_(arena, from.symbol_),
        full_name_(arena, from.full_name_) {}

Security::Security(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Security& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Security_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Security* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.current_price_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.current_price_)
                : nullptr;
  _impl_.current_pe_ratio_ = from._impl_.current_pe_ratio_;

  // @@protoc_insertion_point(copy_constructor:service.Security)
}
PROTOBUF_NDEBUG_INLINE Security::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        symbol_(arena),
        full_name_(arena) {}

inline void Security::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, current_price_),
           0,
           offsetof(Impl_, current_pe_ratio_) -
               offsetof(Impl_, current_price_) +
               sizeof(Impl_::current_pe_ratio_));
}
Security::~Security() {
  // @@protoc_insertion_point(destructor:service.Security)
  SharedDtor(*this);
}
inline void Security::SharedDtor(MessageLite& self) {
  Security& this_ = static_cast<Security&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.symbol_.Destroy();
  this_._impl_.full_name_.Destroy();
  delete this_._impl_.current_price_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Security::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Security(arena);
}
constexpr auto Security::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Security),
                                            alignof(Security));
}
constexpr auto Security::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Security_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Security::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Security>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Security::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Security>(), &Security::ByteSizeLong,
              &Security::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Security, _impl_._cached_size_),
          false,
      },
      &Security::kDescriptorMethods,
      &descriptor_table_service_2fsecurity_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Security_class_data_ =
        Security::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Security::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Security_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Security_class_data_.tc_table);
  return Security_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 40, 2>
Security::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Security, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Security_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::Security>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float current_pe_ratio = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(Security, _impl_.current_pe_ratio_)}},
    // string symbol = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Security, _impl_.symbol_)}},
    // string full_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(Security, _impl_.full_name_)}},
    // .common.Money current_price = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(Security, _impl_.current_price_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string symbol = 1;
    {PROTOBUF_FIELD_OFFSET(Security, _impl_.symbol_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string full_name = 2;
    {PROTOBUF_FIELD_OFFSET(Security, _impl_.full_name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .common.Money current_price = 3;
    {PROTOBUF_FIELD_OFFSET(Security, _impl_.current_price_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // float current_pe_ratio = 4;
    {PROTOBUF_FIELD_OFFSET(Security, _impl_.current_pe_ratio_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::common::Money>()},
  }},
  {{
    "\20\6\11\0\0\0\0\0"
    "service.Security"
    "symbol"
    "full_name"
  }},
};
PROTOBUF_NOINLINE void Security::Clear() {
// @@protoc_insertion_point(message_clear_start:service.Security)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.symbol_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.full_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.current_price_ != nullptr);
      _impl_.current_price_->Clear();
    }
  }
  _impl_.current_pe_ratio_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Security::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Security& this_ = static_cast<const Security&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Security::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Security& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:service.Security)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string symbol = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_symbol().empty()) {
      const ::std::string& _s = this_._internal_symbol();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.Security.symbol");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string full_name = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_full_name().empty()) {
      const ::std::string& _s = this_._internal_full_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.Security.full_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .common.Money current_price = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.current_price_, this_._impl_.current_price_->GetCachedSize(), target,
        stream);
  }

  // float current_pe_ratio = 4;
  if ((cached_has_bits & 0x00000008u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_current_pe_ratio()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_current_pe_ratio(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.Security)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Security::ByteSizeLong(const MessageLite& base) {
  const Security& this_ = static_cast<const Security&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Security::ByteSizeLong() const {
  const Security& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:service.Security)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // string symbol = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_symbol().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_symbol());
      }
    }
    // string full_name = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_full_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_full_name());
      }
    }
    // .common.Money current_price = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.current_price_);
    }
    // float current_pe_ratio = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_current_pe_ratio()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Security::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Security*>(&to_msg);
  auto& from = static_cast<const Security&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:service.Security)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_symbol().empty()) {
        _this->_internal_set_symbol(from._internal_symbol());
      } else {
        if (_this->_impl_.symbol_.IsDefault()) {
          _this->_internal_set_symbol("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_full_name().empty()) {
        _this->_internal_set_full_name(from._internal_full_name());
      } else {
        if (_this->_impl_.full_name_.IsDefault()) {
          _this->_internal_set_full_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.current_price_ != nullptr);
      if (_this->_impl_.current_price_ == nullptr) {
        _this->_impl_.current_price_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.current_price_);
      } else {
        _this->_impl_.current_price_->MergeFrom(*from._impl_.current_price_);
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_current_pe_ratio()) != 0) {
        _this->_impl_.current_pe_ratio_ = from._impl_.current_pe_ratio_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Security::CopyFrom(const Security& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.Security)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Security::InternalSwap(Security* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.full_name_, &other->_impl_.full_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Security, _impl_.current_pe_ratio_)
      + sizeof(Security::_impl_.current_pe_ratio_)
      - PROTOBUF_FIELD_OFFSET(Security, _impl_.current_price_)>(
          reinterpret_cast<char*>(&_impl_.current_price_),
          reinterpret_cast<char*>(&other->_impl_.current_price_));
}

::google::protobuf::Metadata Security::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace service
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_service_2fsecurity_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
