// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service/security.proto
#ifndef GRPC_service_2fsecurity_2eproto__INCLUDED
#define GRPC_service_2fsecurity_2eproto__INCLUDED

#include "service/security.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace service {

// *******************************
// * Securities APIs and objects *
// *******************************
class SecurityService final {
 public:
  static constexpr char const* service_full_name() {
    return "service.SecurityService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::service::GetSecurityResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetSecurityResponse>> AsyncGetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetSecurityResponse>>(AsyncGetSecurityRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetSecurityResponse>> PrepareAsyncGetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::GetSecurityResponse>>(PrepareAsyncGetSecurityRaw(context, request, cq));
    }
    virtual ::grpc::Status ListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::service::ListSecuritiesResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListSecuritiesResponse>> AsyncListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListSecuritiesResponse>>(AsyncListSecuritiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListSecuritiesResponse>> PrepareAsyncListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::service::ListSecuritiesResponse>>(PrepareAsyncListSecuritiesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest* request, ::service::GetSecurityResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest* request, ::service::GetSecurityResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest* request, ::service::ListSecuritiesResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest* request, ::service::ListSecuritiesResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::GetSecurityResponse>* AsyncGetSecurityRaw(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::GetSecurityResponse>* PrepareAsyncGetSecurityRaw(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::ListSecuritiesResponse>* AsyncListSecuritiesRaw(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::service::ListSecuritiesResponse>* PrepareAsyncListSecuritiesRaw(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::service::GetSecurityResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetSecurityResponse>> AsyncGetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetSecurityResponse>>(AsyncGetSecurityRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetSecurityResponse>> PrepareAsyncGetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::GetSecurityResponse>>(PrepareAsyncGetSecurityRaw(context, request, cq));
    }
    ::grpc::Status ListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::service::ListSecuritiesResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListSecuritiesResponse>> AsyncListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListSecuritiesResponse>>(AsyncListSecuritiesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListSecuritiesResponse>> PrepareAsyncListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::service::ListSecuritiesResponse>>(PrepareAsyncListSecuritiesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest* request, ::service::GetSecurityResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSecurity(::grpc::ClientContext* context, const ::service::GetSecurityRequest* request, ::service::GetSecurityResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest* request, ::service::ListSecuritiesResponse* response, std::function<void(::grpc::Status)>) override;
      void ListSecurities(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest* request, ::service::ListSecuritiesResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::service::GetSecurityResponse>* AsyncGetSecurityRaw(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::GetSecurityResponse>* PrepareAsyncGetSecurityRaw(::grpc::ClientContext* context, const ::service::GetSecurityRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::ListSecuritiesResponse>* AsyncListSecuritiesRaw(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::service::ListSecuritiesResponse>* PrepareAsyncListSecuritiesRaw(::grpc::ClientContext* context, const ::service::ListSecuritiesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSecurity_;
    const ::grpc::internal::RpcMethod rpcmethod_ListSecurities_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSecurity(::grpc::ServerContext* context, const ::service::GetSecurityRequest* request, ::service::GetSecurityResponse* response);
    virtual ::grpc::Status ListSecurities(::grpc::ServerContext* context, const ::service::ListSecuritiesRequest* request, ::service::ListSecuritiesResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSecurity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSecurity() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSecurity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSecurity(::grpc::ServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSecurity(::grpc::ServerContext* context, ::service::GetSecurityRequest* request, ::grpc::ServerAsyncResponseWriter< ::service::GetSecurityResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListSecurities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListSecurities() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListSecurities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSecurities(::grpc::ServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSecurities(::grpc::ServerContext* context, ::service::ListSecuritiesRequest* request, ::grpc::ServerAsyncResponseWriter< ::service::ListSecuritiesResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSecurity<WithAsyncMethod_ListSecurities<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetSecurity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSecurity() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::service::GetSecurityRequest, ::service::GetSecurityResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::service::GetSecurityRequest* request, ::service::GetSecurityResponse* response) { return this->GetSecurity(context, request, response); }));}
    void SetMessageAllocatorFor_GetSecurity(
        ::grpc::MessageAllocator< ::service::GetSecurityRequest, ::service::GetSecurityResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::service::GetSecurityRequest, ::service::GetSecurityResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSecurity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSecurity(::grpc::ServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSecurity(
      ::grpc::CallbackServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListSecurities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListSecurities() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::service::ListSecuritiesRequest, ::service::ListSecuritiesResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::service::ListSecuritiesRequest* request, ::service::ListSecuritiesResponse* response) { return this->ListSecurities(context, request, response); }));}
    void SetMessageAllocatorFor_ListSecurities(
        ::grpc::MessageAllocator< ::service::ListSecuritiesRequest, ::service::ListSecuritiesResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::service::ListSecuritiesRequest, ::service::ListSecuritiesResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListSecurities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSecurities(::grpc::ServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListSecurities(
      ::grpc::CallbackServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetSecurity<WithCallbackMethod_ListSecurities<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSecurity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSecurity() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSecurity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSecurity(::grpc::ServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListSecurities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListSecurities() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListSecurities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSecurities(::grpc::ServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSecurity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSecurity() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSecurity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSecurity(::grpc::ServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSecurity(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListSecurities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListSecurities() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListSecurities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSecurities(::grpc::ServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSecurities(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSecurity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSecurity() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSecurity(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSecurity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSecurity(::grpc::ServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSecurity(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListSecurities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListSecurities() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListSecurities(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListSecurities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSecurities(::grpc::ServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListSecurities(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSecurity : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSecurity() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::service::GetSecurityRequest, ::service::GetSecurityResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::service::GetSecurityRequest, ::service::GetSecurityResponse>* streamer) {
                       return this->StreamedGetSecurity(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSecurity() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSecurity(::grpc::ServerContext* /*context*/, const ::service::GetSecurityRequest* /*request*/, ::service::GetSecurityResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSecurity(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::service::GetSecurityRequest,::service::GetSecurityResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListSecurities : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListSecurities() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::service::ListSecuritiesRequest, ::service::ListSecuritiesResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::service::ListSecuritiesRequest, ::service::ListSecuritiesResponse>* streamer) {
                       return this->StreamedListSecurities(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListSecurities() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListSecurities(::grpc::ServerContext* /*context*/, const ::service::ListSecuritiesRequest* /*request*/, ::service::ListSecuritiesResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListSecurities(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::service::ListSecuritiesRequest,::service::ListSecuritiesResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSecurity<WithStreamedUnaryMethod_ListSecurities<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSecurity<WithStreamedUnaryMethod_ListSecurities<Service > > StreamedService;
};

}  // namespace service


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_service_2fsecurity_2eproto__INCLUDED
