// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: stockmarket.proto
#ifndef GRPC_stockmarket_2eproto__INCLUDED
#define GRPC_stockmarket_2eproto__INCLUDED

#include "stockmarket.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class StockMarket final {
 public:
  static constexpr char const* service_full_name() {
    return "StockMarket";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetStock(::grpc::ClientContext* context, const ::GetStockRequest& request, ::GetStockResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetStockResponse>> AsyncGetStock(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetStockResponse>>(AsyncGetStockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetStockResponse>> PrepareAsyncGetStock(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetStockResponse>>(PrepareAsyncGetStockRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetStock(::grpc::ClientContext* context, const ::GetStockRequest* request, ::GetStockResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStock(::grpc::ClientContext* context, const ::GetStockRequest* request, ::GetStockResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GetStockResponse>* AsyncGetStockRaw(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GetStockResponse>* PrepareAsyncGetStockRaw(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetStock(::grpc::ClientContext* context, const ::GetStockRequest& request, ::GetStockResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetStockResponse>> AsyncGetStock(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetStockResponse>>(AsyncGetStockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetStockResponse>> PrepareAsyncGetStock(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetStockResponse>>(PrepareAsyncGetStockRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetStock(::grpc::ClientContext* context, const ::GetStockRequest* request, ::GetStockResponse* response, std::function<void(::grpc::Status)>) override;
      void GetStock(::grpc::ClientContext* context, const ::GetStockRequest* request, ::GetStockResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GetStockResponse>* AsyncGetStockRaw(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GetStockResponse>* PrepareAsyncGetStockRaw(::grpc::ClientContext* context, const ::GetStockRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetStock_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetStock(::grpc::ServerContext* context, const ::GetStockRequest* request, ::GetStockResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStock() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStock(::grpc::ServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStock(::grpc::ServerContext* context, ::GetStockRequest* request, ::grpc::ServerAsyncResponseWriter< ::GetStockResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetStock<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStock() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::GetStockRequest, ::GetStockResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GetStockRequest* request, ::GetStockResponse* response) { return this->GetStock(context, request, response); }));}
    void SetMessageAllocatorFor_GetStock(
        ::grpc::MessageAllocator< ::GetStockRequest, ::GetStockResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GetStockRequest, ::GetStockResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStock(::grpc::ServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStock(
      ::grpc::CallbackServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetStock<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStock() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStock(::grpc::ServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStock() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStock(::grpc::ServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStock() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStock(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStock(::grpc::ServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStock() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GetStockRequest, ::GetStockResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GetStockRequest, ::GetStockResponse>* streamer) {
                       return this->StreamedGetStock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStock(::grpc::ServerContext* /*context*/, const ::GetStockRequest* /*request*/, ::GetStockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GetStockRequest,::GetStockResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetStock<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetStock<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_stockmarket_2eproto__INCLUDED
